apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: my-database
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS my_db;
    USE my_db;

    CREATE TABLE user_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

    INSERT INTO user_table (name) VALUES ('John Doe');

