name: Build and Push Docker Image

on:
  push:
    branches:
      - main # or your default branch
  # Optionally, you can use a different trigger, such as on every push to any branch or on a schedule
  # schedule:
  #   - cron: '0 0 * * *' # This will run daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/apache-mysql-k8s-new:latest
       
